name: aegisub-procles
base: core24
version: 3.4.2-snap
summary: Advanced subtitle editor
description: |
 Originally created as tool to make typesetting, particularly in anime
 fansubs, a less painful experience, Aegisub has grown into a fully
 fledged, highly customizable subtitle editor.

 It features a lot of convenient tools to help you with timing,
 typesetting, editing and translating subtitles, as well as a powerful
 scripting environment called Automation (originally mostly intended for
 creating karaoke effects, Automation can now be used much else, including
 creating macros and various other convenient tools).

 This is an unofficial snap, the developers may not be responsible for any bugs in it. For any bug reports: https://github.com/vcprocles/aegisub-procles-snap
grade: stable
confinement: strict
compression: lzo
#platforms:
      #- build-on: [amd64]
      #  build-for: [amd64]
      #- build-on: [arm64]
      #  build-for: [arm64]
      #- build-on: [armhf]
      #  build-for: [armhf]
      #<platform-name>:
      #build-on: <list-of-arch> | <arch>
      #build-for: <list-of-arch> | <arch>
      

parts:
  aegisub-procles:
    plugin: meson
    meson-parameters:
    - --prefix=/usr/local
    - --buildtype=release
    - --strip
    override-prime: |
      sed -i 's@org.aegisub.Aegisub@/usr/local/share/icons/hicolor/scalable/apps/org.aegisub.Aegisub.svg@g' ../stage/usr/local/share/applications/org.aegisub.Aegisub.desktop
      snapcraftctl prime
    source-type: git
    source: https://github.com/TypesettingTools/Aegisub
    source-tag: v3.4.2
    override-build: |
      snapcraftctl build
    build-packages:
    - libgl-dev
    - libfreetype-dev
    - libfontconfig1-dev
    - libass-dev
    - libboost-dev
    - libboost-chrono-dev
    - libboost-filesystem-dev
    - libboost-locale-dev
    - libboost-regex-dev
    - libboost-system-dev
    - libboost-thread-dev
    - libffms2-dev
    - libwxgtk3.2-dev
    - intltool
    - luajit
    - libluajit-5.1-dev
    - libhunspell-dev
    - libfftw3-dev
    - libuchardet-dev
    - libpulse-dev
    - libicu-dev
    - autopoint
    #stage-packages:
    #- libass9
    #- libboost-chrono1.83.0
    #- libboost-filesystem1.83.0
    #- libboost-locale1.83.0
    #- libboost-regex1.83.0
    #- libboost-thread1.83.0
    #- libffms2-5
    #- libfftw3-double3
    #- libfontconfig1
    #- libgl1
    #- libhunspell-1.7-0
    #- libicu74
    #- libluajit-5.1-2
    #- libpulse0
    #- libwxbase3.2-1t64
    #- libwxgtk3.2-1t64
    #- libwxgtk-gl3.2-1t64
    #- libsndio7.0
    #- libuchardet0
#    filesets:
#      fset:
#      - usr/bin/*
#      - usr/lib/*
#      - usr/libexec/*
#      - usr/local/*
#      - usr/sbin/*
#      - usr/share/*
#      - -usr/share/doc/*
#    stage: [$fset]
#    prime: [$fset]
  move-scripts:
    plugin: dump
    source: .
    organize:
      move_scripts.sh: bin/

apps:
  aegisub-procles:
    extensions: [gnome]
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu/pulseaudio/ #dirty fix for pulse .so being not found
      DISABLE_WAYLAND: 1
    command: usr/local/bin/aegisub
    desktop: usr/local/share/applications/org.aegisub.Aegisub.desktop
    common-id: aegisub.desktop
    plugs:
      - audio-playback
      - home
      - opengl
      - removable-media
  move-scripts:
    command: bin/move_scripts.sh
